// CinemaBox APK based provider v1.0
var TMDB_KEY="ee8ac8a9044c09a11cc362033f98c735";
var BASES=["https://pucinema.albox.co/api/v4/","https://cinema.albox.co/api/v4/"];
var ORDER={"4K":0,"1080p":1,"720p":2,"480p":3,"360p":4,"240p":5,"HLS":6,"HD":7};
function clean(s){return String(s||"").replace(/\\\//g,"/").replace(/&amp;/g,"&").replace(/\\u0026/g,"&");}
function norm(s){return String(s||"").toLowerCase().replace(/[’'`]/g,"").replace(/[^a-z0-9\u0600-\u06FF]+/g," ").replace(/\s+/g," ").trim();}
function add(a,v){v=String(v||"").trim();if(!v)return;if(a.indexOf(v)<0)a.push(v);var x=v.replace(/[’'`]/g,"").replace(/\s+/g," ").trim();if(x&&a.indexOf(x)<0)a.push(x);x=v.replace(/[’'`]/g," ").replace(/\s+/g," ").trim();if(x&&a.indexOf(x)<0)a.push(x);}
async function fj(u){var r=await fetch(u,{headers:{Accept:"application/json, text/plain, */*"}});if(!r||!r.ok)return null;return await r.json();}
async function tmdb(id,type){var k=String(type).toLowerCase()==="movie"?"movie":"tv";var u="https://api.themoviedb.org/3/"+k+"/"+id+"?api_key="+TMDB_KEY;var en=await fj(u+"&language=en").catch(function(){return{};})||{};var ar=await fj(u+"&language=ar").catch(function(){return{};})||{};var t=[];add(t,en.title);add(t,en.original_title);add(t,en.name);add(t,en.original_name);add(t,ar.title);add(t,ar.original_title);add(t,ar.name);add(t,ar.original_name);return t;}
function arr(d){return Array.isArray(d)?d:(d&&(d.results||d.data||d.items||d.shows||d.result))||[];}
function gid(x){return x&&(x.id||x.show_id||x.post_id||x.nb||x._id||x.uuid||x.season_id||x.seasonId||null);}
function title(x){return x&&(x.name||x.title||x.en_name||x.ar_name||x.original_name||x.post_title||x.show_name||"");}
function titleOK(x,titles){var a=norm(title(x));if(!a)return false;for(var i=0;i<titles.length;i++){var b=norm(titles[i]);if(!b)continue;if(a===b||a.indexOf(b)>=0||b.indexOf(a)>=0)return true;}return false;}
function q(u){var s=String(u||"").toLowerCase();if(/4k|2160/.test(s))return"4K";if(/1080/.test(s))return"1080p";if(/720/.test(s))return"720p";if(/480/.test(s))return"480p";if(/360/.test(s))return"360p";if(/240/.test(s))return"240p";if(/m3u8/.test(s))return"HLS";return"HD";}
function collectUrls(n,out){if(n==null)return;if(typeof n==="string"){var r=/https?:\/\/[^\s"'<>\\]+(?:\.mp4|\.m3u8)(?:\?[^\s"'<>\\]*)?/gi,m,s=clean(n);while((m=r.exec(s))!==null)out.push(m[0]);return;}if(Array.isArray(n)){for(var i=0;i<n.length;i++)collectUrls(n[i],out);return;}if(typeof n==="object"){var ks=Object.keys(n);for(var k=0;k<ks.length;k++)collectUrls(n[ks[k]],out);}}
function streams(n){var u=[];collectUrls(n,u);var out=[],seen={};for(var i=0;i<u.length;i++){var x=u[i];if(!x||seen[x]||/trailer|thumb|poster|preview/i.test(x))continue;seen[x]=1;var qu=q(x);out.push({title:"CinemaBox "+qu,name:"CinemaBox",provider:"CinemaBox",url:x,quality:qu,type:x.indexOf(".m3u8")>-1?"hls":"direct"});}return out.sort(function(a,b){return((ORDER[a.quality]!=null)?ORDER[a.quality]:99)-((ORDER[b.quality]!=null)?ORDER[b.quality]:99);});}
function num(x,ks){for(var i=0;i<ks.length;i++){var v=x&&x[ks[i]];if(v==null)continue;var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10);}return null;}
function epNo(x){var n=num(x,["episode_number","episodeNumber","episode_num","ep_num","episodeNo","episode","ep","number"]);if(n)return n;var txt=clean([x&&x.name,x&&x.title,x&&x.slug].join(" "));var m=txt.match(/[sS]\s*0*\d+\s*[eE]\s*0*(\d+)/);return m?parseInt(m[1],10):null;}
function seasonNo(x){return num(x,["__season","season_number","seasonNumber","season_num","seasonNo","season"]);}
function collectEpisodes(n,out,parent){if(!n||typeof n!=="object")return;if(Array.isArray(n)){for(var i=0;i<n.length;i++)collectEpisodes(n[i],out,parent);return;}var s=seasonNo(n)||parent||null;var e=epNo(n);var has=streams(n).length>0;if((gid(n)||has)&&e){n.__season=s;out.push(n);}var ks=Object.keys(n);for(var k=0;k<ks.length;k++)collectEpisodes(n[ks[k]],out,s);}
function collectSeasons(n,out){if(!n||typeof n!=="object")return;if(Array.isArray(n)){for(var i=0;i<n.length;i++)collectSeasons(n[i],out);return;}var sid=n.season_id||n.seasonId||null;var sn=seasonNo(n);if(sid&&sn)out.push({id:sid,season:sn});var ks=Object.keys(n);for(var k=0;k<ks.length;k++)collectSeasons(n[ks[k]],out);}
async function detail(base,id){var u=[base+"shows/shows/dynamic/"+id,base+"shows/shows/"+id,base+"shows/show/"+id,base+"show/"+id];for(var i=0;i<u.length;i++){var d=await fj(u[i]).catch(function(){return null;});if(d){if(d.data&&!Array.isArray(d.data))d=d.data;if(d.result&&!Array.isArray(d.result))d=d.result;return d;}}return null;}
async function player(base,id){var u=[base+"shows/episodes/player/"+id,base+"shows/seasons/player/"+id];for(var i=0;i<u.length;i++){var d=await fj(u[i]).catch(function(){return null;});var s=d?streams(d):[];if(s.length)return s;var eps=[];collectEpisodes(d,eps,null);if(eps.length)return eps;}return[];}
async function findInDetail(base,d,s,e){var eps=[];collectEpisodes(d,eps,null);for(var i=0;i<eps.length;i++){var en=epNo(eps[i]),sn=seasonNo(eps[i]);if(en===e&&(sn==null||sn===s)){var st=streams(eps[i]);if(st.length)return st;var eid=gid(eps[i]);if(eid){var ps=await player(base,eid);if(Array.isArray(ps)&&ps.length&&ps[0].url)return ps;}}}var seas=[];collectSeasons(d,seas);for(var j=0;j<seas.length;j++){if(seas[j].season!==s)continue;var r=await player(base,seas[j].id);if(Array.isArray(r)&&r.length){if(r[0].url)return r;for(var k=0;k<r.length;k++){if(epNo(r[k])===e){var st2=streams(r[k]);if(st2.length)return st2;}}}}return[];}
async function searchBase(base,titles,s,e){for(var qi=0;qi<titles.length&&qi<5;qi++){var term=encodeURIComponent(titles[qi]);var urls=[base+"search?query="+term,base+"search?q="+term,base+"search?keyword="+term];for(var ui=0;ui<urls.length;ui++){var rs=arr(await fj(urls[ui]).catch(function(){return null;}));for(var i=0;i<rs.length;i++){var id=gid(rs[i]);if(!id||!titleOK(rs[i],titles))continue;var d=await detail(base,id);if(!d)continue;var out=await findInDetail(base,d,s,e);if(out.length)return out;}}}return[];}
async function getStreams(tmdbId,mediaType,season,episode){try{var titles=await tmdb(tmdbId,mediaType);var s=parseInt(season,10)||1,e=parseInt(episode,10)||1;for(var b=0;b<BASES.length;b++){var out=await searchBase(BASES[b],titles,s,e);if(out.length)return out;}return[];}catch(err){return[];}}
module.exports={getStreams:getStreams};
