// CinemaBox Provider — Iraq Scrapers v4.5.1 exact episode only
var TMDB_KEY="ee8ac8a9044c09a11cc362033f98c735";
var API="https://cinema.albox.co/api/v4/";
var ORDER={"4K":0,"1080p":1,"720p":2,"480p":3,"360p":4,"240p":5,"HLS":6,"HD":7};
function norm(s){return String(s||"").toLowerCase().replace(/[’'`]/g,"").replace(/[^a-z0-9\u0600-\u06FF]+/g," ").replace(/\s+/g," ").trim();}
function add(a,v){v=String(v||"").trim();if(v&&a.indexOf(v)<0)a.push(v);var x=v.replace(/[’'`]/g,"").trim();if(x&&a.indexOf(x)<0)a.push(x);}
async function fetchJson(u){var r=await fetch(u,{headers:{Accept:"application/json, text/plain, */*","User-Agent":"Mozilla/5.0"}});if(!r||!r.ok)return null;return await r.json();}
async function getTitles(id,type){var k=String(type).toLowerCase()==="movie"?"movie":"tv",u="https://api.themoviedb.org/3/"+k+"/"+id+"?api_key="+TMDB_KEY;var en=await fetchJson(u+"&language=en").catch(function(){return{};})||{},ar=await fetchJson(u+"&language=ar").catch(function(){return{};})||{},out=[];add(out,en.title);add(out,en.original_title);add(out,en.name);add(out,en.original_name);add(out,ar.title);add(out,ar.original_title);add(out,ar.name);add(out,ar.original_name);return out;}
function arr(d){return Array.isArray(d)?d:(d&&(d.results||d.data||d.items||d.posts||d.shows||d.result))||[];}
function itemId(x){return x&&(x.id||x.show_id||x.post_id||x.nb||x._id||x.uuid||x.episode_id||x.episodeId||null);}
function itemTitle(x){return x&&(x.name||x.title||x.en_name||x.ar_name||x.original_name||x.post_title||x.show_name||"");}
function titleOk(x,titles){var a=norm(itemTitle(x));if(!a)return false;for(var i=0;i<titles.length;i++){var b=norm(titles[i]);if(b&&(a===b||a.indexOf(b)>=0||b.indexOf(a)>=0))return true;}return false;}
async function detail(id){var urls=[API+"shows/shows/dynamic/"+id,API+"shows/show/"+id,API+"show/"+id];for(var i=0;i<urls.length;i++){var d=await fetchJson(urls[i]).catch(function(){return null;});if(!d)continue;if(d.data&&!Array.isArray(d.data))d=d.data;if(d.result&&!Array.isArray(d.result))d=d.result;return d;}return null;}
function num(x,keys){for(var i=0;i<keys.length;i++){var v=x&&x[keys[i]];if(v==null)continue;var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10);}return null;}
function epNo(x){return num(x,["episode_number","episodeNumber","episode_num","ep_num","episodeNo","episode","number"]);}
function seasonNo(x){return num(x,["season_number","seasonNumber","season_num","seasonNo","season"]);}
function collectEpisodes(node,out,parentSeason){if(!node||typeof node!=="object")return;if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectEpisodes(node[i],out,parentSeason);return;}var s=seasonNo(node)||parentSeason||null,e=epNo(node),id=itemId(node),card=String(node.card_type||node.type||"").toLowerCase();if(id&&(e||card.indexOf("episode")>=0)){node.__season=s;out.push(node);}var ks=Object.keys(node);for(var k=0;k<ks.length;k++)collectEpisodes(node[ks[k]],out,s);}
function q(url){var t=String(url||"").toLowerCase();if(/4k|2160/.test(t))return"4K";if(/1080/.test(t))return"1080p";if(/720/.test(t))return"720p";if(/480/.test(t))return"480p";if(/360/.test(t))return"360p";if(/240/.test(t))return"240p";if(/m3u8/.test(t))return"HLS";return"HD";}
function collectUrls(node,out){if(node==null)return;if(typeof node==="string"){var s=String(node).replace(/\\\//g,"/").replace(/&amp;/g,"&"),r=/https?:\/\/[^\s"'<>\\]+(?:\.mp4|\.m3u8)(?:\?[^\s"'<>\\]*)?/gi,m;while((m=r.exec(s))!==null)out.push(m[0]);return;}if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectUrls(node[i],out);return;}if(typeof node==="object"){var ks=Object.keys(node);for(var k=0;k<ks.length;k++)collectUrls(node[ks[k]],out);}}
function streamsFrom(data){var urls=[];collectUrls(data,urls);var out=[],seen={};for(var i=0;i<urls.length;i++){var u=urls[i];if(!u||seen[u]||/trailer|thumb|poster|preview/i.test(u))continue;seen[u]=1;var qu=q(u);out.push({title:"CinemaBox "+qu,name:"CinemaBox",provider:"CinemaBox",url:u,quality:qu,type:u.indexOf(".m3u8")>-1?"hls":"direct"});}return out.sort(function(a,b){return((ORDER[a.quality]!=null)?ORDER[a.quality]:99)-((ORDER[b.quality]!=null)?ORDER[b.quality]:99);});}
async function player(id){var urls=[API+"shows/episodes/player/"+id,API+"episodes/player/"+id,API+"player/"+id];for(var i=0;i<urls.length;i++){var d=await fetchJson(urls[i]).catch(function(){return null;});var s=d?streamsFrom(d):[];if(s.length)return s;}return[];}
async function tvStreams(d,s,e){var eps=[];collectEpisodes(d,eps,null);for(var i=0;i<eps.length;i++){var ep=eps[i],sn=seasonNo(ep)||ep.__season||s,en=epNo(ep);if(sn===s&&en===e){var direct=streamsFrom(ep);if(direct.length)return direct;var id=itemId(ep);return id?player(id):[];}}return[];}
async function searchOne(query,titles,season,episode){var urls=[API+"search?q="+encodeURIComponent(query),API+"search?keyword="+encodeURIComponent(query),API+"shows/search?q="+encodeURIComponent(query)];for(var u=0;u<urls.length;u++){var rs=arr(await fetchJson(urls[u]).catch(function(){return null;}));for(var i=0;i<rs.length;i++){if(!itemId(rs[i])||!titleOk(rs[i],titles))continue;var d=await detail(itemId(rs[i]));if(!d)continue;var st=await tvStreams(d,season,episode);if(st.length)return st;}}return[];}
async function getStreams(tmdbId,mediaType,season,episode){try{var titles=await getTitles(tmdbId,mediaType),s=parseInt(season,10)||1,e=parseInt(episode,10)||1;for(var i=0;i<titles.length;i++){var st=await searchOne(titles[i],titles,s,e);if(st.length)return st;}return[];}catch(err){return[];}}
module.exports={getStreams:getStreams};
