// CinemaBox provider v1.7 subtitles
var K="ee8ac8a9044c09a11cc362033f98c735",A="https://cinema.albox.co/api/v4/";
async function J(u){var r=await fetch(u,{headers:{Accept:"application/json, text/plain, */*","User-Agent":"Mozilla/5.0"}});return r&&r.ok?await r.json():null}
function N(s){return String(s||"").toLowerCase().replace(/[’'`]/g,"").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").trim()}
function ARR(x){return Array.isArray(x)?x:(x&&(x.results||x.data||x.items||x.posts||x.shows||x.result))||[]}
function ID(x){return x&&(x.id||x.show_id||x.post_id||x.nb||x._id||x.uuid)}
function TIT(x){return String((x&&(x.name||x.title||x.en_name||x.ar_name||x.original_name||x.post_title||x.show_name||x.show_title))||"")}
function NUM(x,ks){for(var i=0;i<ks.length;i++){var v=x&&x[ks[i]];if(v!=null){var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10)}}return null}
function EP(x){return NUM(x,["episode_number","episodeNumber","description","title","episode"])}
function SN(x){return NUM(x,["season_number","seasonNumber","season","number","title"])}
function OK(x,ts){var a=N(TIT(x));for(var i=0;i<ts.length;i++){var b=N(ts[i]);if(b&&(a==b||a.indexOf(b)>=0||b.indexOf(a)>=0))return true}return false}
function SUB(data){var r=[];(function w(x){if(!x)return;if(Array.isArray(x)){for(var i=0;i<x.length;i++)w(x[i]);return}if(typeof x==="object"){if(x.srt)r.push({url:x.srt,lang:x.language||"ar",language:x.language||"ar",title:"Arabic",format:"srt"});if(x.vtt)r.push({url:x.vtt,lang:x.language||"ar",language:x.language||"ar",title:"Arabic",format:"vtt"});if(x.subtitles)w(x.subtitles)}})(data);return r}
function V(data){var out=[],subs=SUB(data),tracks=[];for(var s=0;s<subs.length;s++)tracks.push({file:subs[s].url,label:subs[s].title||"Arabic",kind:"subtitles",srclang:subs[s].lang||"ar",default:s==0});(function walk(x){if(!x)return;if(Array.isArray(x)){for(var i=0;i<x.length;i++)walk(x[i]);return}if(typeof x==="object"){if(x.url&&/^https?:/.test(x.url)){var q=x.quality||(/1080/.test(x.url)?"1080p":/720/.test(x.url)?"720p":/480/.test(x.url)?"480p":"HD"),st={title:"CinemaBox "+q,name:"CinemaBox",provider:"CinemaBox",url:x.url,quality:q,type:x.url.indexOf(".m3u8")>-1?"hls":"direct"};if(subs.length){st.subtitles=subs;st.tracks=tracks;st.subtitle=subs[0].url;st.subUrl=subs[0].url}out.push(st)}if(x.videos)walk(x.videos)}})(data);return out}
async function TM(id,mediaType){var u="https://api.themoviedb.org/3/"+(mediaType==="movie"?"movie":"tv")+"/"+id+"?api_key="+K,a=[],e=await J(u+"&language=en").catch(function(){return{}})||{},r=await J(u+"&language=ar").catch(function(){return{}})||{};function add(v){v=String(v||"").trim();if(v&&a.indexOf(v)<0)a.push(v);v=v.replace(/[’'`]/g,"");if(v&&a.indexOf(v)<0)a.push(v)}add(e.title);add(e.original_title);add(e.name);add(e.original_name);add(r.title);add(r.original_title);add(r.name);add(r.original_name);return a}
async function D(show,season){var d=await J(A+"shows/shows/dynamic/"+show+(season?"?season_id="+season:"")).catch(function(){return null});if(d&&d.data&&!Array.isArray(d.data))d=d.data;if(d&&d.result&&!Array.isArray(d.result))d=d.result;return d}
function seasons(x,o){if(!x||typeof x!=="object")return;if(Array.isArray(x)){for(var i=0;i<x.length;i++)seasons(x[i],o);return}var ct=String(x.card_type||x.type||"").toLowerCase(),s=SN(x);if(s&&ct.indexOf("season")>=0&&ID(x))o.push({s:s,id:ID(x)});var ks=Object.keys(x);for(var k=0;k<ks.length;k++)seasons(x[ks[k]],o)}
function eps(x,o){if(!x||typeof x!=="object")return;if(Array.isArray(x)){for(var i=0;i<x.length;i++)eps(x[i],o);return}var ct=String(x.card_type||x.type||"").toLowerCase(),e=EP(x);if(e&&ct.indexOf("episode")>=0&&ID(x))o.push({e:e,id:ID(x)});var ks=Object.keys(x);for(var k=0;k<ks.length;k++)eps(x[ks[k]],o)}
async function F(eid,e){var d=await J(A+"shows/episodes/"+eid+"/files").catch(function(){return null});if(!d)return[];var t=d;if(Array.isArray(d.episodes)){for(var i=0;i<d.episodes.length;i++)if(EP(d.episodes[i])===e)t=d.episodes[i]}return V(t)}
async function find(show,s,e){var d=await D(show,0),ss=[];seasons(d,ss);for(var i=0;i<ss.length;i++)if(ss[i].s===s){var dd=await D(show,ss[i].id),es=[];eps(dd,es);for(var k=0;k<es.length;k++)if(es[k].e===e)return F(es[k].id,e)}return[]}
async function S(term){var q=encodeURIComponent(term),u=["shows/search?q=","search?q=","search?query=","search?term=","search?search_term="];var all=[];for(var i=0;i<u.length;i++){var r=ARR(await J(A+u[i]+q).catch(function(){return null}));for(var k=0;k<r.length;k++)all.push(r[k])}return all}
async function getStreams(tmdbId,mediaType,season,episode){try{var ts=await TM(tmdbId,mediaType),s=parseInt(season,10)||1,e=parseInt(episode,10)||1;for(var t=0;t<ts.length;t++){var rs=await S(ts[t]);for(var i=0;i<rs.length;i++)if(ID(rs[i])&&OK(rs[i],ts)){var o=await find(ID(rs[i]),s,e);if(o.length)return o}}return[]}catch(err){return[]}}
module.exports={getStreams:getStreams};
