// Cinemana Provider — subtitles v1.8.0
var K="ee8ac8a9044c09a11cc362033f98c735",A="https://cinemana.shabakaty.cc/api/android/",Q={"1080p":0,"720p":1,"480p":2,"360p":3,"240p":4,"HLS":5,"HD":6};
function nq(q){if(!q)return"HD";if(typeof q==="number")return q+"p";return String(q).replace(/\s/g,"")}
function sort(s){return s.sort(function(a,b){return(Q[a.quality]!=null?Q[a.quality]:9)-(Q[b.quality]!=null?Q[b.quality]:9)})}
function n(s){return String(s||"").toLowerCase().replace(/[’'`]/g,"").replace(/[^\w\s\u0600-\u06FF]/g,"").replace(/\s+/g," ").trim()}
function rt(r){return[r.name,r.title,r.en_title,r.ar_title,r.other_title,r.enTitle,r.arTitle].filter(Boolean).join(" ")}
function sim(a,b){a=n(a);b=n(b);if(!a||!b)return 0;if(a===b)return 1;if(a.indexOf(b)>=0||b.indexOf(a)>=0)return .85;var A=a.split(" "),B=b.split(" "),c=0;for(var i=0;i<A.length;i++)for(var j=0;j<B.length;j++)if(A[i]===B[j]&&A[i].length>1){c++;break}return 2*c/(A.length+B.length)}
function bs(ts,t){var b=0;for(var i=0;i<ts.length;i++){var s=sim(ts[i],t);if(s>b)b=s}return b}
function num(x,ks){for(var i=0;i<ks.length;i++){var v=x&&x[ks[i]];if(v!=null){var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10)}}return null}
function tm(id,type){var p="/"+(type==="movie"?"movie":"tv")+"/"+id,b="https://api.themoviedb.org/3"+p+"?api_key="+K;return Promise.all([fetch(b+"&language=en").then(function(r){return r.json()}).catch(function(){return{}}),fetch(b+"&language=ar").then(function(r){return r.json()}).catch(function(){return{}})]).then(function(r){var e=r[0],a=r[1],t=[];function add(x){x=String(x||"").trim();if(x&&t.indexOf(x)<0)t.push(x);x=x.replace(/[’'`]/g,"").trim();if(x&&t.indexOf(x)<0)t.push(x)}add(e.title);add(e.original_title);add(e.name);add(e.original_name);add(a.title);add(a.original_title);add(a.name);add(a.original_name);var d=e.release_date||e.first_air_date||"";return{titles:t.filter(Boolean),year:d?parseInt(d.substring(0,4)):null}})}
function pick(rs,ts,y){if(!rs||!rs.length)return null;var sc=[];for(var i=0;i<rs.length;i++){var r=rs[i],s=bs(ts,rt(r));if(s<.35)continue;if(r.rootSeries==="0"||r.rootSeries===0)s+=.15;if(y&&r.year){var yy=parseInt(r.year);if(yy===y)s+=.3;else if(Math.abs(yy-y)===1)s+=.1;else if(Math.abs(yy-y)>2)s-=.2}sc.push({r:r,s:s})}if(!sc.length)return null;sc.sort(function(a,b){return b.s-a.s});return sc[0].r}
function getStreams(id,type,season,episode){return tm(id,type).then(function(d){if(!d.titles.length)return[];return search(d.titles,d.year,0,type==="movie"?"movies":"series",season,episode)}).catch(function(){return[]})}
function search(ts,y,i,type,season,episode){if(i>=ts.length)return Promise.resolve([]);return fetch(A+"AdvancedSearch?videoTitle="+encodeURIComponent(ts[i])+"&type="+type).then(function(r){return r.json()}).then(function(rs){if(!rs||!rs.length)return search(ts,y,i+1,type,season,episode);var m=pick(rs,ts,y);if(!m)return search(ts,y,i+1,type,season,episode);var nb=m.rootSeries&&m.rootSeries!=="0"?m.rootSeries:m.nb;if(type==="series"&&season&&episode)return tv(nb,parseInt(season)||1,parseInt(episode)||1);return files(m.nb||nb)}).catch(function(){return search(ts,y,i+1,type,season,episode)})}
function tv(show,s,e){return fetch(A+"videoSeason/id/"+show).then(function(r){return r.json()}).then(function(d){if(!d||!d.length)return[];var flat=d[0]&&d[0].episodeNummer!=null,eps=[];if(flat)eps=d;else{var sd=null;for(var i=0;i<d.length;i++){var sn=num(d[i],["season","seasonNumber","title"])||(i+1);if(sn===s){sd=d[i];break}}if(!sd&&d.length>=s)sd=d[s-1];if(!sd)return[];eps=sd.episodes||sd.videos||[]}var nb=null;for(var j=0;j<eps.length;j++){var sn2=num(eps[j],["season","seasonNumber"]),en=num(eps[j],["episodeNummer","episodeNumber","episode","title","orderNmmer"])||(j+1);if((!sn2||sn2===s)&&en===e){nb=eps[j].nb;break}}if(!nb&&!flat&&eps.length>=e)nb=eps[e-1].nb;return nb?files(nb):[]}).catch(function(){return[]})}
function subs(nb){return fetch(A+"translationFiles/id/"+nb).then(function(r){return r.text()}).then(function(t){t=String(t||"").replace(/\\\//g,"/");var out=[],m,re=/https?:\/\/[^"'\s<>]+\.(?:vtt|srt)(?:\?[^"'\s<>]*)?/gi;while((m=re.exec(t))){var u=m[0],lang=/_en_|en_trans/i.test(u)?"en":"ar",fmt=/\.srt/i.test(u)?"srt":"vtt",title=lang==="en"?"English":"Arabic";if(!out.some(function(x){return x.url===u}))out.push({url:u,lang:lang,language:lang,title:title,format:fmt})}out.sort(function(a,b){return a.lang==="ar"?-1:b.lang==="ar"?1:0});return out}).catch(function(){return[]})}
function att(st,s){if(!s||!s.length)return st;var tr=[];for(var i=0;i<s.length;i++)tr.push({file:s[i].url,label:s[i].title,kind:"subtitles",srclang:s[i].lang,default:i===0});st.subtitles=s;st.tracks=tr;st.subtitle=s[0].url;st.subUrl=s[0].url;return st}
function files(nb){return Promise.all([fetch(A+"transcoddedFiles/id/"+nb).then(function(r){return r.json()}).catch(function(){return[]}),subs(nb)]).then(function(res){var fs=Array.isArray(res[0])?res[0]:[],s=res[1]||[],st=[],seen={};for(var i=0;i<fs.length;i++){var f=fs[i],u=f.videoUrl||f.url||f.transcoddedFile||"",q=nq(f.resolution||f.quality||f.name||"HD");if(u&&!seen[u]){seen[u]=1;st.push(att({title:"Cinemana "+q,name:"Cinemana",provider:"Cinemana",url:u,quality:q,type:u.indexOf(".m3u8")>-1?"hls":"direct"},s))}}return sort(st)}).catch(function(){return[]})}
module.exports={getStreams:getStreams};
