// CinemaBox Provider — strict episode matching v1.0.0
var TMDB_KEY="ee8ac8a9044c09a11cc362033f98c735";
var API="https://cinema.albox.co/api/v4/";
var ORDER={"4K":0,"2160p":0,"1080p":1,"720p":2,"480p":3,"360p":4,"240p":5,"HLS":6,"HD":7};
function clean(s){return String(s||"").replace(/\\\//g,"/").replace(/&amp;/g,"&").replace(/\\u0026/g,"&");}
function q(url,label){var t=(String(label||"")+" "+String(url||"")).toLowerCase();if(/2160p|4k|uhd/.test(t))return"4K";if(/1080p|1080/.test(t))return"1080p";if(/720p|720/.test(t))return"720p";if(/480p|480/.test(t))return"480p";if(/360p|360/.test(t))return"360p";if(/240p|240/.test(t))return"240p";if(/m3u8|hls/.test(t))return"HLS";return"HD";}
function sort(a){return a.sort(function(x,y){return(ORDER[x.quality]!=null?ORDER[x.quality]:99)-(ORDER[y.quality]!=null?ORDER[y.quality]:99);});}
function norm(s){return String(s||"").toLowerCase().replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06FF\s]/g," ").replace(/\s+/g," ").trim();}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 1;if(a.indexOf(b)>-1||b.indexOf(a)>-1)return .86;var aa=a.split(" "),bb=b.split(" "),c=0;for(var i=0;i<aa.length;i++){for(var j=0;j<bb.length;j++){if(aa[i].length>1&&aa[i]===bb[j]){c++;break;}}}return(2*c)/(aa.length+bb.length);}
function bestScore(titles,target){var b=0;for(var i=0;i<titles.length;i++){var s=sim(titles[i],target);if(s>b)b=s;}return b;}
async function fj(url){var r=await fetch(url,{headers:{Accept:"application/json, text/plain, */*"}});if(!r||!r.ok)return null;return await r.json();}
async function tmdb(id,type){var path="/"+(String(type).toLowerCase()==="movie"?"movie":"tv")+"/"+id;var base="https://api.themoviedb.org/3"+path+"?api_key="+TMDB_KEY;var en=await fj(base+"&language=en").catch(function(){return{};})||{};var ar=await fj(base+"&language=ar").catch(function(){return{};})||{};var titles=[];function add(x){if(x&&titles.indexOf(x)===-1)titles.push(x);}add(en.title);add(en.original_title);add(en.name);add(en.original_name);add(ar.title);add(ar.original_title);add(ar.name);add(ar.original_name);var ds=en.release_date||en.first_air_date||ar.release_date||ar.first_air_date||"";return{titles:titles.filter(Boolean),year:ds?parseInt(String(ds).slice(0,4),10):null};}
function arr(d){if(!d)return[];if(Array.isArray(d))return d;return d.results||d.data||d.items||d.posts||d.shows||d.result||[];}
function title(x){return x&&(x.name||x.title||x.en_name||x.ar_name||x.original_name||x.post_title||x.show_name||"");}
function year(x){var m=String(x&&(x.year||x.release_year||x.production_year||x.date||x.release_date||x.first_air_date)||"").match(/(19|20)\d{2}/);return m?parseInt(m[0],10):null;}
function idOf(x){return x&&(x.id||x.show_id||x.post_id||x.nb||x._id||x.uuid||null);}
function typeOf(x){var r=String(x&&(x.type||x.kind||x.category||x.post_type||x.media_type)||"").toUpperCase();if(r.indexOf("MOVIE")>-1||r.indexOf("FILM")>-1)return"MOVIE";if(r.indexOf("SERIES")>-1||r.indexOf("SHOW")>-1||r.indexOf("TV")>-1)return"SERIES";return r;}
function pick(results,titles,yr,mediaType){var target=String(mediaType).toLowerCase()==="movie"?"MOVIE":"SERIES",best=null,bv=-9;for(var i=0;i<results.length;i++){var r=results[i],id=idOf(r);if(!id)continue;var sc=bestScore(titles,title(r));var tp=typeOf(r);if(tp&&tp!==target)sc-=.55;if(yr){var ry=year(r);if(ry===yr)sc+=.35;else if(ry&&Math.abs(ry-yr)>2)sc-=.25;}if(sc>bv){bv=sc;best=r;}}return best&&bv>=.35?best:null;}
async function detail(id){var urls=[API+"shows/shows/dynamic/"+id,API+"shows/show/"+id,API+"show/"+id];for(var i=0;i<urls.length;i++){var d=await fj(urls[i]).catch(function(){return null;});if(!d)continue;if(d.data&&!Array.isArray(d.data))d=d.data;if(d.result&&!Array.isArray(d.result))d=d.result;if(d.post_info||d.sections||d.seasons||d.episodes||d.videos||d.data)return d;}return null;}
function text(x){return clean([x&&x.name,x&&x.title,x&&x.en_name,x&&x.ar_name,x&&x.post_title,x&&x.slug,x&&x.url,x&&x.link].join(" "));}
function num(x,fields){for(var i=0;i<fields.length;i++){var v=x&&x[fields[i]];if(v==null||v==="")continue;var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10);}return null;}
function seasonNo(x){return num(x,["__s","season_number","seasonNumber","season_num","seasonNo"]);}
function epNo(x){var n=num(x,["episode_number","episodeNumber","episode_num","ep_num","episodeNo","episode","ep","number"]);if(n)return n;var t=text(x),m=t.match(/[sS]\s*0*\d+\s*[eE]\s*0*(\d{1,3})/);if(m)return parseInt(m[1],10);m=t.match(/(?:episode|ep|الحلقه|الحلقة)\s*0*(\d{1,3})/i);return m?parseInt(m[1],10):null;}
function exactText(t,s,e){t=clean(t);return new RegExp("[sS]\\s*0*"+s+"\\s*[eE]\\s*0*"+e+"(?![0-9])").test(t)||new RegExp("season\\s*0*"+s+"[^0-9]{0,20}(episode|ep)\\s*0*"+e+"(?![0-9])","i").test(t);}
function seasonHint(x,parent){var n=num(x,["season_number","seasonNumber","season_num","seasonNo"]);if(n)return n;var m=text(x).match(/(?:season|الموسم)\s*0*(\d{1,2})/i);return m?parseInt(m[1],10):(parent||null);}
function collectEpisodes(node,out,parent){if(!node||typeof node!=="object")return;if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectEpisodes(node[i],out,parent);return;}var s=seasonHint(node,parent);var id=idOf(node);var card=String(node.card_type||node.type||"").toLowerCase();var looks=!!epNo(node)||card.indexOf("episode")>-1||exactText(text(node),s||0,epNo(node)||0);if(id&&looks){if(s&&!node.__s)node.__s=s;out.push(node);}var keys=Object.keys(node);for(var k=0;k<keys.length;k++)collectEpisodes(node[keys[k]],out,s);}
function matchEp(x,s,e){if(exactText(text(x),s,e))return true;var en=epNo(x);if(en!==e)return false;var sn=seasonNo(x);return sn==null||sn===s;}
function collectUrls(node,out){if(node==null)return;if(typeof node==="string"){var re=/https?:\/\/[^\s"'<>\\]+(?:\.mp4|\.m3u8)(?:\?[^\s"'<>\\]*)?/gi,m,t=clean(node);while((m=re.exec(t))!==null)out.push(m[0]);return;}if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectUrls(node[i],out);return;}if(typeof node==="object"){var keys=Object.keys(node);for(var k=0;k<keys.length;k++)collectUrls(node[keys[k]],out);}}
function streamsFrom(data){var urls=[];collectUrls(data,urls);var out=[],seen={};for(var i=0;i<urls.length;i++){var u=urls[i];if(!u||seen[u]||/trailer|thumb|poster|preview/i.test(u))continue;seen[u]=true;var qu=q(u,"");out.push({title:"CinemaBox "+qu,name:"CinemaBox",provider:"CinemaBox",url:u,quality:qu,type:u.indexOf(".m3u8")>-1?"hls":"direct"});}return sort(out);}
async function player(epId){var urls=[API+"shows/episodes/player/"+epId,API+"episodes/player/"+epId,API+"player/"+epId];for(var i=0;i<urls.length;i++){var d=await fj(urls[i]).catch(function(){return null;});if(!d)continue;var s=streamsFrom(d);if(s.length)return s;}return[];}
async function tv(detailObj,s,e){var eps=[];collectEpisodes(detailObj,eps,null);var ep=null;for(var i=0;i<eps.length;i++){if(matchEp(eps[i],s,e)){ep=eps[i];break;}}if(!ep)return[];var direct=streamsFrom(ep);if(direct.length)return direct;var eid=idOf(ep);return eid?player(eid):[];}
async function searchCB(query,titles,yr,mediaType,season,episode){var urls=[API+"search?q="+encodeURIComponent(query),API+"search?keyword="+encodeURIComponent(query),API+"shows/search?q="+encodeURIComponent(query)];for(var i=0;i<urls.length;i++){var rs=arr(await fj(urls[i]).catch(function(){return null;}));if(!rs.length)continue;var m=pick(rs,titles,yr,mediaType);if(!m)continue;var d=await detail(idOf(m));if(!d)continue;if(String(mediaType).toLowerCase()==="movie"){var p=(d.post_info||d.postInfo||d.info||d);var eid=p.episode_id||p.episodeId||p.default_episode_id||p.id;var ms=eid?await player(eid):streamsFrom(d);if(ms.length)return ms;}else{var ts=await tv(d,parseInt(season,10)||1,parseInt(episode,10)||1);if(ts.length)return ts;}}return[];}
async function getStreams(tmdbId,mediaType,season,episode){try{var d=await tmdb(tmdbId,mediaType);for(var i=0;i<d.titles.length;i++){var s=await searchCB(d.titles[i],d.titles,d.year,mediaType,season,episode);if(s.length)return s;}return[];}catch(e){return[];}}
module.exports={getStreams:getStreams};
