// Cinemana Provider — flat episode list v1.7.0
var TMDB_KEY = "ee8ac8a9044c09a11cc362033f98c735";
var API = "https://cinemana.shabakaty.com/api/android/";
var QUALITY_ORDER = { "1080p": 0, "720p": 1, "480p": 2, "360p": 3, "240p": 4, "HLS": 5, "HD": 6 };
function normalizeQuality(q) { if (!q) return "HD"; if (typeof q === "number") return q + "p"; return String(q).replace(/\s/g, ""); }
function sortByQuality(streams) { return streams.sort(function(a, b) { var oa = QUALITY_ORDER[a.quality] != null ? QUALITY_ORDER[a.quality] : 9; var ob = QUALITY_ORDER[b.quality] != null ? QUALITY_ORDER[b.quality] : 9; return oa - ob; }); }
function norm(s) { return (s || "").toLowerCase().replace(/[’'`]/g, "").replace(/[^\w\s\u0600-\u06FF]/g, "").replace(/\s+/g, " ").trim(); }
function resultTitle(r) { return [r.name, r.title, r.en_title, r.ar_title, r.other_title, r.enTitle, r.arTitle].filter(Boolean).join(" "); }
function similarity(a, b) { a = norm(a); b = norm(b); if (!a || !b) return 0; if (a === b) return 1; if (a.indexOf(b) >= 0 || b.indexOf(a) >= 0) return 0.85; var setA = a.split(" "), setB = b.split(" "); var common = 0; for (var i = 0; i < setA.length; i++) { for (var j = 0; j < setB.length; j++) { if (setA[i] === setB[j] && setA[i].length > 1) { common++; break; } } } return (2 * common) / (setA.length + setB.length); }
function bestScore(titles, target) { var best = 0; for (var i = 0; i < titles.length; i++) { var s = similarity(titles[i], target); if (s > best) best = s; } return best; }
function num(x, keys) { for (var i = 0; i < keys.length; i++) { var v = x && x[keys[i]]; if (v != null) { var m = String(v).match(/\d+/); if (m) return parseInt(m[0], 10); } } return null; }
function fetchTMDBData(tmdbId, mediaType) { var path = "/" + (mediaType === "movie" ? "movie" : "tv") + "/" + tmdbId; var base = "https://api.themoviedb.org/3" + path + "?api_key=" + TMDB_KEY; return Promise.all([fetch(base + "&language=en").then(function(r) { return r.json(); }).catch(function() { return {}; }), fetch(base + "&language=ar").then(function(r) { return r.json(); }).catch(function() { return {}; })]).then(function(res) { var en = res[0], ar = res[1]; var titles = []; function add(t) { t = String(t || "").trim(); if (t && titles.indexOf(t) === -1) titles.push(t); var x = t.replace(/[’'`]/g, "").trim(); if (x && titles.indexOf(x) === -1) titles.push(x); } add(en.title); add(en.original_title); add(en.name); add(en.original_name); add(ar.title); add(ar.original_title); add(ar.name); add(ar.original_name); var dateStr = en.release_date || en.first_air_date || ""; var year = dateStr ? parseInt(dateStr.substring(0, 4)) : null; return { titles: titles.filter(Boolean), year: year }; }); }
function pickBestMatch(results, titles, year) { if (!results || !results.length) return null; var scored = []; for (var i = 0; i < results.length; i++) { var r = results[i]; var score = bestScore(titles, resultTitle(r)); if (score < 0.35) continue; if (r.rootSeries === "0" || r.rootSeries === 0) score += 0.15; if (year && r.year) { var resultYear = parseInt(r.year); if (resultYear === year) score += 0.3; else if (Math.abs(resultYear - year) === 1) score += 0.1; else if (Math.abs(resultYear - year) > 2) score -= 0.2; } scored.push({ result: r, score: score }); } if (!scored.length) return results[0]; scored.sort(function(a, b) { return b.score - a.score; }); return scored[0].result; }
function getStreams(tmdbId, mediaType, season, episode) { return fetchTMDBData(tmdbId, mediaType).then(function(data) { if (!data.titles.length) return []; var type = mediaType === "movie" ? "movies" : "series"; return searchCinemana(data.titles, data.year, 0, type, season, episode); }).catch(function() { return []; }); }
function searchCinemana(titles, year, idx, type, season, episode) { if (idx >= titles.length) return Promise.resolve([]); return fetch(API + "AdvancedSearch?videoTitle=" + encodeURIComponent(titles[idx]) + "&type=" + type).then(function(r) { return r.json(); }).then(function(results) { if (!results || !results.length) return searchCinemana(titles, year, idx + 1, type, season, episode); var match = pickBestMatch(results, titles, year); if (!match) return searchCinemana(titles, year, idx + 1, type, season, episode); var nb = match.rootSeries && match.rootSeries !== "0" ? match.rootSeries : match.nb; if (type === "series" && season && episode) return getTVFiles(nb, parseInt(season) || 1, parseInt(episode) || 1); return getFiles(match.nb || nb); }).catch(function() { return searchCinemana(titles, year, idx + 1, type, season, episode); }); }
function getTVFiles(showNb, sNum, eNum) { return fetch(API + "videoSeason/id/" + showNb).then(function(r) { return r.json(); }).then(function(data) { if (!data || !data.length) return []; var flat = data[0] && data[0].episodeNummer != null; var episodes = []; if (flat) { episodes = data; } else { var seasonData = null; for (var i = 0; i < data.length; i++) { var sn = num(data[i], ["season", "seasonNumber", "title"]) || (i + 1); if (sn === sNum) { seasonData = data[i]; break; } } if (!seasonData && data.length >= sNum) seasonData = data[sNum - 1]; if (!seasonData) return []; episodes = seasonData.episodes || seasonData.videos || []; } if (!episodes.length) return []; var epNb = null; for (var j = 0; j < episodes.length; j++) { var sn2 = num(episodes[j], ["season", "seasonNumber"]); var en = num(episodes[j], ["episodeNummer", "episodeNumber", "episode", "title", "orderNmmer"]) || (j + 1); if ((!sn2 || sn2 === sNum) && en === eNum) { epNb = episodes[j].nb; break; } } if (!epNb && !flat && episodes.length >= eNum) epNb = episodes[eNum - 1].nb; if (!epNb) return []; return getFiles(epNb); }).catch(function() { return []; }); }
function getFiles(nb) { return fetch(API + "transcoddedFiles/id/" + nb).then(function(r) { return r.json(); }).then(function(files) { var streams = [], seen = {}; files = Array.isArray(files) ? files : []; for (var i = 0; i < files.length; i++) { var f = files[i]; var url = f.videoUrl || f.url || f.transcoddedFile || ""; var q = normalizeQuality(f.resolution || f.quality || f.name || "HD"); if (url && !seen[url]) { seen[url] = true; streams.push({ title: "Cinemana " + q, name: "Cinemana", provider: "Cinemana", url: url, quality: q, type: url.indexOf(".m3u8") > -1 ? "hls" : "direct" }); } } return sortByQuality(streams); }).catch(function() { return []; }); }
module.exports = { getStreams: getStreams };
