// CinemaBox strict safe provider v1.1.0
var TMDB_KEY="ee8ac8a9044c09a11cc362033f98c735";
var API="https://cinema.albox.co/api/v4/";
var ORDER={"4K":0,"1080p":1,"720p":2,"480p":3,"360p":4,"240p":5,"HLS":6,"HD":7};
function clean(s){return String(s||"").replace(/\\\//g,"/").replace(/&amp;/g,"&").replace(/\\u0026/g,"&");}
function norm(s){return String(s||"").toLowerCase().replace(/[^a-z0-9\u0600-\u06FF]+/g," ").replace(/\s+/g," ").trim();}
function quality(u){var t=String(u||"").toLowerCase();if(/4k|2160/.test(t))return"4K";if(/1080/.test(t))return"1080p";if(/720/.test(t))return"720p";if(/480/.test(t))return"480p";if(/360/.test(t))return"360p";if(/240/.test(t))return"240p";if(/m3u8/.test(t))return"HLS";return"HD";}
function sort(a){return a.sort(function(x,y){return(ORDER[x.quality]??99)-(ORDER[y.quality]??99);});}
async function json(u){var r=await fetch(u,{headers:{Accept:"application/json, text/plain, */*"}});if(!r||!r.ok)return null;return await r.json();}
function array(d){return Array.isArray(d)?d:(d&&(d.results||d.data||d.items||d.shows||d.result))||[];}
function id(x){return x&&(x.id||x.show_id||x.post_id||x.nb||x._id||null);}
function title(x){return x&&(x.name||x.title||x.en_name||x.ar_name||x.original_name||x.post_title||x.show_name||"");}
async function tmdb(tmdbId,type){var k=String(type).toLowerCase()==="movie"?"movie":"tv";var b="https://api.themoviedb.org/3/"+k+"/"+tmdbId+"?api_key="+TMDB_KEY;var en=await json(b+"&language=en").catch(function(){return{};})||{};var ar=await json(b+"&language=ar").catch(function(){return{};})||{};var a=[];function add(v){if(v&&a.indexOf(v)<0)a.push(v);}add(en.title);add(en.original_title);add(en.name);add(en.original_name);add(ar.title);add(ar.original_title);add(ar.name);add(ar.original_name);return a.filter(Boolean);}
function exactMatch(item,titles){var it=norm(title(item));if(!it)return false;for(var i=0;i<titles.length;i++){var t=norm(titles[i]);if(!t)continue;if(t.length<=4){if(it===t||it.indexOf(t+" ")===0)return true;}else if(it===t||it.indexOf(t)>-1||t.indexOf(it)>-1)return true;}return false;}
async function detail(showId){var urls=[API+"shows/shows/dynamic/"+showId,API+"shows/show/"+showId,API+"show/"+showId];for(var i=0;i<urls.length;i++){var d=await json(urls[i]).catch(function(){return null;});if(!d)continue;if(d.data&&!Array.isArray(d.data))d=d.data;if(d.result&&!Array.isArray(d.result))d=d.result;return d;}return null;}
function blob(x){return clean([x&&x.name,x&&x.title,x&&x.slug,x&&x.url,x&&x.link,x&&x.file,x&&x.src].join(" "));}
function num(x,keys){for(var i=0;i<keys.length;i++){var v=x&&x[keys[i]];if(v==null)continue;var m=String(v).match(/\d+/);if(m)return parseInt(m[0],10);}return null;}
function epNum(x){var n=num(x,["episode_number","episodeNumber","episode_num","ep_num","episodeNo","episode","ep","number"]);if(n)return n;var m=blob(x).match(/[sS]\s*0*\d+\s*[eE]\s*0*(\d+)/);return m?parseInt(m[1],10):null;}
function seasonNum(x){return num(x,["__season","season_number","seasonNumber","season_num","seasonNo","season"]);}
function collectEpisodes(node,out,parent){if(!node||typeof node!=="object")return;if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectEpisodes(node[i],out,parent);return;}var s=seasonNum(node)||parent||null;var e=epNum(node);if(id(node)&&e){if(s&&!node.__season)node.__season=s;out.push(node);}var keys=Object.keys(node);for(var k=0;k<keys.length;k++)collectEpisodes(node[keys[k]],out,s);}
function collectUrls(node,out){if(node==null)return;if(typeof node==="string"){var re=/https?:\/\/[^\s"'<>\\]+(?:\.mp4|\.m3u8)(?:\?[^\s"'<>\\]*)?/gi,m,t=clean(node);while((m=re.exec(t))!==null)out.push(m[0]);return;}if(Array.isArray(node)){for(var i=0;i<node.length;i++)collectUrls(node[i],out);return;}if(typeof node==="object"){var keys=Object.keys(node);for(var k=0;k<keys.length;k++)collectUrls(node[keys[k]],out);}}
function streamsFrom(data){var urls=[];collectUrls(data,urls);var out=[],seen={};for(var i=0;i<urls.length;i++){var u=urls[i];if(!u||seen[u]||/trailer|thumb|poster|preview/i.test(u))continue;seen[u]=1;var q=quality(u);out.push({title:"CinemaBox "+q,name:"CinemaBox",provider:"CinemaBox",url:u,quality:q,type:u.indexOf(".m3u8")>-1?"hls":"direct"});}return sort(out);}
async function player(eid){var urls=[API+"shows/episodes/player/"+eid,API+"episodes/player/"+eid,API+"player/"+eid];for(var i=0;i<urls.length;i++){var d=await json(urls[i]).catch(function(){return null;});var s=d?streamsFrom(d):[];if(s.length)return s;}return[];}
async function findStreams(show,s,e){var d=await detail(show);if(!d)return[];var eps=[];collectEpisodes(d,eps,null);for(var i=0;i<eps.length;i++){var en=epNum(eps[i]),sn=seasonNum(eps[i]);if(en===e&&(sn==null||sn===s)){var st=streamsFrom(eps[i]);if(st.length)return st;return player(id(eps[i]));}}return[];}
async function getStreams(tmdbId,mediaType,season,episode){try{var titles=await tmdb(tmdbId,mediaType);if(!titles.length)return[];var queries=titles.slice(0,2);for(var qi=0;qi<queries.length;qi++){var rs=array(await json(API+"search?q="+encodeURIComponent(queries[qi])).catch(function(){return null;}));for(var i=0;i<rs.length;i++){if(!id(rs[i])||!exactMatch(rs[i],titles))continue;var s=await findStreams(id(rs[i]),parseInt(season,10)||1,parseInt(episode,10)||1);if(s.length)return s;}}return[];}catch(e){return[];}}
module.exports={getStreams:getStreams};
